# Generated by Django 5.0.2 on 2024-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_url', models.CharField(blank=True, choices=[('/index', 'Index'), ('/clients', 'Clients'), ('/contact', 'Contact'), ('/facilities', 'Facilities'), ('/service', 'Service'), ('/gallery', 'Gallery'), ('/partners', 'Partners'), ('/profile', 'Profile'), ('/team', 'Team')], max_length=255, null=True)),
                ('banner_type', models.CharField(blank=True, choices=[('Header', 'Header'), ('Footer', 'Footer'), ('Body', 'Body')], max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
