# Generated by Django 5.0.2 on 2024-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='about',
            field=models.CharField(blank=True, choices=[('Hero banner', 'Hero banner'), ('Body banner', 'Body banner'), ('What we do', 'What we do'), ('What we do content', 'What we do content'), ('Team', 'Team'), ('Partners', 'Partners'), ('Why sigma', 'Why sigma')], max_length=255, null=True),
        ),
    ]
