# Generated by Django 5.0.2 on 2024-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='about',
            field=models.CharField(blank=True, choices=[('Hero banner', 'Hero banner'), ('Body banner', 'Body banner'), ('What we do', 'What we do'), ('What we do content', 'What we do content'), ('Team', 'Team'), ('Partners', 'Partners'), ('Why sigma', 'Why sigma'), ('Get in touch', 'Get in touch'), ('Mission', 'Mission'), ('Vision', 'Vision'), ('Value', 'Value')], max_length=255, null=True),
        ),
    ]
