# Generated by Django 5.0.2 on 2024-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_category',
            field=models.CharField(blank=True, choices=[('Top management team', 'Top management team'), ('Engineering team', 'Engineering team')], max_length=100, null=True),
        ),
    ]
