# Generated by Django 5.0.2 on 2024-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
