# Generated by Django 5.0.2 on 2024-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_settings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='uploads/gallery'),
        ),
    ]
