# Generated by Django 5.0.2 on 2024-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
